### ISSUE TITLE
Wayland

### ISSUE THREAD

**Issue by Ufeldraku** [green-project/green-recorder#1]
Close this issue when the wayland support is alive and kicking.

**Comment by mhsabbagh** [comment]
To be more accurate: "GNOME Shell on Wayland" :)

**Comment by Ufeldraku** [comment]
OH yeah Baby! Gnome Shell + Wayland = new Waifu.
Thanks bro.

**Comment by mhsabbagh** [comment]
Wayland support is now here :)
