### ISSUE TITLE
Not running on MacOS, maybe missing smth

### ISSUE THREAD

**Issue by shershen08** [green-project/green-recorder#12]
I've tried to do manual install with needed packages but failed to find `gir1.2-appindicator3` and `gawk` in pypi.
As a result further `sudo python setup.py install` and trying to run green-recorder/build/scripts-3.5/green-recorder results in:
```
 File "green-recorder/build/scripts-3.5/green-recorder", line 133
    print "No pulseaudio found", output.returncode
                              ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by mhsabbagh** [comment]
Green recorder was designed to work on Linux systems only. Probably it won't work on Mac. You won't find those dependences in Python, they are usually installed from your packaging manager. 

However. the current problem you have is that you are trying to use Python 3 to run the program. The recorder was written with Python 2 only. So you have to run it like `python2 gree-recorder` or something according to how you do it on Mac. But again, probably it won't work.

**Comment by shershen08** [comment]
I see, thanks for the details. I'll try with Python 2 and get back with the results.
