### ISSUE TITLE
no way to stop recording

### ISSUE THREAD

**Issue by kparal** [green-project/green-recorder#17]
I just tried green-recorder on Fedora 25. It records video just fine, but there's no way to stop it. I'm using Wayland, and there's no icon in the system tray area, and clicking on the orange circle in the top right corner (using any mouse button) doesn't stop it either. Hopefully I started it from the terminal, so I was able to stop it using Ctrl+C.

green-recorder-2.2-1.fc25.noarch

**Comment by mhsabbagh** [comment]
You shouldn't run "green-recorder" from the terminal window on Wayland. Because we need to set env GDK_BACKEND=x11 before running it. This is already set in the desktop file. So you should run it using the application icon from the menu only.

Try that and tell me. You will notice that an indicator in the notifications area is started.

**Comment by kparal** [comment]
Great, that works.

I have two suggestions how to improve this:
a) detect wayland in the `/usr/bin/green-recorder` script before you import required libraries and set the environment variable from it. That way it will work also from terminal out of the box. Or if that's too complicated, create a new launcher that will just do this and execute the real executable.
b) If there are reasons for not doing a), at least print a warning into terminal if you detect that you're running on wayland without the envvar set.

Thanks a lot. And thanks for developing this tool!

**Comment by mhsabbagh** [comment]
Thank you, definitely will take that into the to-do list :)

**Comment by kparal** [comment]
If you don't want to lose track of it, you can simply keep this open and just rename the title. That's what issues are for. It also helps anyone having a similar problem to find a solution (until it is fixed in code). Just a hint :)

**Comment by kparal** [comment]
It would be better if you set `GDK_BACKEND=x11` during program start. Then people wouldn't need to care about it at all:
http://stackoverflow.com/questions/5971312/how-to-set-environment-variables-in-python

**Comment by drkitty28** [comment]
Love this recorder but do wish there was a system tray icon to control start & stop. Otherwise, green recorder dialog appears in the capture (even when window to record is selected).  Any workaround?

**Comment by drkitty28** [comment]
Or even shortcut keys?
