### ISSUE TITLE
No module named pydbus

### ISSUE THREAD

**Issue by Ufeldraku** [green-project/green-recorder#19]
> Traceback
 (most recent call last):
  File "/usr/bin/green-recorder", line 23, in <module>
    from pydbus import SessionBus
ImportError: No module named pydbus

Fresh Arch Linux install, installed from AUR.

**Comment by mhsabbagh** [comment]
Weird. That Python module is already set as a dependency in the package: https://aur.archlinux.org/packages/python-pydbus/

To solve your problem, run sudo pip install pydbus

**Comment by Ufeldraku** [comment]
The git one.
Runnin that command doesn't solve it.

**Comment by mhsabbagh** [comment]
Then you are probably using Python 3 instead of Python 2 by default on your system. It won't work with Python 3

**Comment by Ufeldraku** [comment]
So, how to solve it? Arch uses python 3 by default.

**Comment by gort818** [comment]
@Ufeldraku I have an arch system I will test later and find a solution for you.

**Comment by Ufeldraku** [comment]
I installed python2-pip and then did the same thing above but with pip2, and it actually fixed it.

**Comment by gort818** [comment]
@unixfox green-recorder-git in the aur needs be changed, dependency should be python2-pydbus instead of python-pydbus.

That should fix the problem for future users @Ufeldraku @mhsabbagh

**Comment by unixfox** [comment]
@gort818 I'm so sorry, I forgot to add the "2" of the package name. It's fixed.

**Comment by mhsabbagh** [comment]
Thank you all for taking time for this :-)

**Comment by unixfox** [comment]
@mhsabbagh No problem, don't forget to readd the guide for ArchLinux.
PS: You don't need to remove the guide for ArchLinux each time the package has to be reupdated because I'm always available quickly to update the package.

**Comment by gort818** [comment]
@mhsabbagh No problem, this is why Linux users are the best :)
@unixfox  Thanks for the quick fix!

**Comment by mhsabbagh** [comment]
@unixfox Thank you, added it back :)
