### ISSUE TITLE
Indicator Question

### ISSUE THREAD

**Issue by rstreeter** [green-project/green-recorder#2]
When the recording starts the indicator is huge, how can I make it smaller? Does it use a specific icon?

**Comment by mhsabbagh** [comment]
Hello.

Can you please attach a screenshot for the "huge indicator"?

**Comment by rstreeter** [comment]
Will post one as soon as I get home. Sorry for not posting one when I submitted the issue.

**Comment by rstreeter** [comment]
![screenshot at 18-07-38](https://cloud.githubusercontent.com/assets/500779/22717459/d84b0190-ed60-11e6-97f6-d8f23defff16.png)

**Comment by mhsabbagh** [comment]
Oh. I see now. Probably this is because of the svg file. Will replace it with a normal png in the next update (around 1-2 days) and fix it. Thank you for your kind report :)

**Comment by rstreeter** [comment]
No problem.
