### ISSUE TITLE
Icon not showing up

### ISSUE THREAD

**Issue by wolfv** [green-project/green-recorder#20]
I'm runnning Fedora 25 and Gnome Shell under Wayland. Unfortunately the Icon isn't showing up in the upper right corner. 

Any ideas? Maybe it would be good if there was an alternate keyboard combination one could use to cancel the recording.

Otherwise, thanks for the neat application! 

Wolf

**Comment by mhsabbagh** [comment]
Check #17 to see if it matches with your situation. Did you install the program from the copr repo?

**Comment by wolfv** [comment]
I checked but unfortunately it doesn't seem to be the same thing for me. 

Yep, installed from copr. Also rebooted computer etc. to check if that makes a difference.

**Comment by wolfv** [comment]
well, weird. Tried again right now and it worked. Magic!
