### ISSUE TITLE
Arch, i3, wont start - folderchooser.set_uri(...) TypeError

### ISSUE THREAD

**Issue by DoTheEvo** [green-project/green-recorder#21]
```
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 202, in <module>
    folderchooser.set_uri("file://" + VideosFolder)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
archlinux, installed from AUR
i3wm at version 4.12
first attempt run through rofi launcher, then tried run in terminal to see whats the issue.

**Comment by gort818** [comment]
Try running it with python2

**Comment by DoTheEvo** [comment]
like this?

![nope](http://i.imgur.com/rnIodjT.png)

**Comment by gort818** [comment]
Hmmm. Can you confirm you have GLib installed? Maybe they don't place nice together, I will look into this.

**Comment by gort818** [comment]
Just tested on arch with i3, no issues on my end.

**Comment by mhsabbagh** [comment]
I am gonna assume this is from the user's side then.

Thank you all.
