### ISSUE TITLE
If a headset is connected the sound is still recorded from the speaker

### ISSUE THREAD

**Issue by AhmedAtef07** [green-project/green-recorder#27]
Should record the sound going to the headset instead.

Ubuntu 16.04
Version: 2.1

**Comment by AhmedAtef07** [comment]
I am recording the mic as well.

**Comment by mhsabbagh** [comment]
Sorry I couldn't understand a word from what you are saying.

**Comment by AhmedAtef07** [comment]
Oh, sorry about that. 
If I am connecting my headphones to the laptop, and started the recording, the application doesn't capture the sound going to the headphones. 
After testing, I figured out that the application only records the sound going to the speakers. 

I am suggesting adding an option to choose the sound source to capture the sound from. Or better capture the sound going to all output sounds. 

The thing is I am not sure if there is any detection if the audio cable is connected or not.

Hope it is clear now.

**Comment by mhsabbagh** [comment]
Green Recorder listen only on the default channel you have on your system. If you are recording using pulseaudio, you could use pavucontrol to change the default channel into microphone/speakers or anything you want. Then Green recorder will automatically use it.
