### ISSUE TITLE
error Appindicator3

### ISSUE THREAD

**Issue by vbextreme** [green-project/green-recorder#28]
I have build and install on Fedora 25, but when try to run get this message
```
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 20, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

```

**Comment by julianrichen** [comment]
Do you have `libappindicator` and `libappindicator-gtk3` installed on Fedora?

**Comment by vbextreme** [comment]
Ok, it works, it would be to add in README.md Other Distributions, dependencies.
very good, but I can't stop recording with right click, but only with CTRL+C

**Comment by julianrichen** [comment]
It's listed as a dep on the fedora .spec file. I would recommend installing the package with that.

**Comment by mhsabbagh** [comment]
You are missing the package libappindicator-gtk3, it is already mentioned in the README file (but with a similar name due do difference in name between distributions).
