### ISSUE TITLE
Unable to record: ffmpeg error

### ISSUE THREAD

**Issue by Nicolas01** [green-project/green-recorder#31]
Here is my output when I start green-recorder
```
/bin/sh: xdpyinfo: command not found
aserver aserver.c:1033:(main) you need to specify server name
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.
```
Here is my output when I start the recording
```
1
ffmpeg version 3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.1 (GCC) 20170306
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-netcdf --enable-shared --enable-version3
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
:0: Invalid argument
ffmpeg not running for some reason. Up you can see the output of ffmpeg.
```
I am on Archlinux. When I installed green-record with the [AUR package](https://aur.archlinux.org/packages/green-recorder-git/), I had to remove the `xorg-utils` dependency because it no longer exists.

**Comment by mhsabbagh** [comment]
Oh, not that's a problem. Green Recorder depends on xdpyinfo in order to retrieve information about the screen. If you removed the xorg-utils package, you won't be able to use the program.

@unixfox Do you know anything about why xorg-utils package was removed from Arch and how we can find an alternative for it in order to include it in the AUR package?

**Comment by unixfox** [comment]
`xorg-utils` was removed from AUR and migrate as a meta package, source: https://www.reddit.com/r/archlinux/comments/69r15f/xorgserverutils_removed/dh8rl34/
So I removed yesterday this package from the dependencies of the package `green-recorder-git`.

**Comment by Nicolas01** [comment]
@mhsabbagh , @unixfox , thanks a lot for your explanation and your fix.
I managed to install `green-recorder` with the updated package from `AUR` and it works smoothly!

**Comment by mhsabbagh** [comment]
Thanks @unixfox and @Nicolas01  :-)
