### ISSUE TITLE
The name org.gnome.Shell.Screencast was not provided by any .service files

### ISSUE THREAD

**Issue by Yailm** [green-project/green-recorder#35]
I've got a problem using green-recorder

    Traceback (most recent call last):
      File "/usr/bin/green-recorder", line 43, in <module>
        calling = bus.get('org.gnome.Shell.Screencast', '/org/gnome/Shell/Screencast')
      File "/usr/lib/python2.7/site-packages/pydbus/proxy.py", line 47, in get
         0, timeout_to_glib(timeout), None)
    GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name 
    org.gnome.Shell.Screencast was not provided by any .service files (2)

Did it mean that I should install gnome where I can use this recorder ?

**Comment by orschiro** [comment]
What desktop environment are you using?

**Comment by Yailm** [comment]
[sway](https://github.com/SirCmpwn/sway)

**Comment by mhsabbagh** [comment]
Yes. Green Recorder only supports GNOME Wayland compositor. You can't use it to record Sway.

**Comment by Yailm** [comment]
Okay...Thank you all the same.
