### ISSUE TITLE
noise in the recorder video

### ISSUE THREAD

**Issue by wael-Fadlallah** [green-project/green-recorder#4]
**Hello** 

> First thanks alots for this amazing program 

So I have failed in record in **mp4** the output file is 0 bit and its completely empty 
but its works in **avi** 
the real issues that the output video contain _noise_ 
Good luck mate

**Comment by mhsabbagh** [comment]
Hello.

Can you please open `green-recorder` from the command line interface and record using the MP4 format and put the output here? Also, what options did you choose when recording? Do you use built-in microphone or something?

**Comment by wael-Fadlallah** [comment]
` wael  ~  green-recorder

(green-recorder:18218): Gtk-WARNING **: Theme directory apps/16x16 of theme ElGeneral has no size field


(green-recorder:18218): Gtk-WARNING **: Theme directory apps/24x24 of theme ElGeneral has no size field


(green-recorder:18218): Gtk-WARNING **: Theme directory apps/32x32 of theme ElGeneral has no size field


(green-recorder:18218): Gtk-WARNING **: Theme directory apps/64x64 of theme ElGeneral has no size field


(green-recorder:18218): Gtk-WARNING **: Theme directory apps/96x96 of theme ElGeneral has no size field


(green-recorder:18218): Gtk-WARNING **: Theme directory apps/192x192 of theme ElGeneral has no size field


(green-recorder:18218): Gtk-WARNING **: Theme directory apps/symbolic of theme ElGeneral has no size field


(green-recorder:18218): Gtk-WARNING **: Theme directory status/scalable of theme ElGeneral has no size field


(green-recorder:18218): Gtk-WARNING **: Theme directory status/symbolic of theme ElGeneral has no size field

ffmpeg version 2.8.10 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.1 (GCC) 20160406 (Red Hat 5.3.1-6)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib --mandir=/usr/share/man --arch=i686 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables' --extra-ldflags='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' --enable-bzlib --disable-crystalhd --enable-frei0r --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopencv --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib --cpu=i686 --enable-runtime-cpudetect
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, x11grab, from ':0.0':
  Duration: N/A, start: 1486732303.895444, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1366x768, 30 fps, 30 tbr, 1000k tbn, 30 tbc

(green-recorder:18218): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Guessed Channel Layout for  Input Stream #1.0 : 5.0
Input #1, alsa, from 'default':
  Duration: N/A, start: 1486732304.091685, bitrate: 3840 kb/s
    Stream #1:0: Audio: pcm_s16le, 48000 Hz, 5 channels, s16, 3840 kb/s
No pixel format specified, yuv444p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[libx264 @ 0x81420680] -qscale is ignored, -crf is recommended.
[libx264 @ 0x81420680] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
[libx264 @ 0x81420680] profile High 4:4:4 Predictive, level 3.2, 4:4:4 8-bit
[libx264 @ 0x81420680] 264 - core 148 r2699 a5e06b9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[aac @ 0x814214a0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
ffmpeg: no process found

`

**Comment by wael-Fadlallah** [comment]
I just check in Record  Microphone 
and I already try to it in a build-in Microphone and  a normal phone Microphone and the result is the same

**Comment by mhsabbagh** [comment]
Yes, you are using ffmpeg 2.x which is an old version of the library. Green recorder was designed to work with ffmpeg 3.x. You can search online for any trusted .Deb package for ffmpeg 3.x and install it.

**Comment by mhsabbagh** [comment]
The package was uploaded to the PPA by the way. If you are using 16.04 or Linux Mint. You can try again.
