### ISSUE TITLE
Animated GIF export?

### ISSUE THREAD

**Issue by orschiro** [green-project/green-recorder#5]
Dear all, 

What a promising project! :-)

Would it be possible to export videos as animated GIF files?

Yours,

Robert

**Comment by mhsabbagh** [comment]
Hello friend :)

Yes, GIF support as on the to-do list. Just give us some time to achieve it :)

Greetings.

**Comment by orschiro** [comment]
Wow, fantastic.

Thank you, Hanny! :-)
